const fs=require("fs"),b=".planning/phases/01-auth",A=[];
A.push("---");A.push("phase: 01-auth");A.push("plan: A");A.push("type: execute");A.push("wave: 1");A.push("depends_on: []");
A.push("files_modified:");A.push("  - gradle/libs.versions.toml");A.push("  - app/build.gradle");A.push("  - app/src/main/java/com/mindJellyProject/mindjelly/common/SessionManager.java");
A.push("autonomous: true");A.push("requirements:");A.push("  - AUTH-03");A.push("  - QUAL-05");A.push("");
A.push("must_haves:");A.push("  truths:");
A.push("    - "앱 재시작 후에도 JWT 토큰이 EncryptedSharedPreferences에서 복원된다"");
A.push("    - "SessionManager.getToken()이 저장된 토큰 문자열을 반환한다"");
A.push("    - "SessionManager.getUserId()가 JWT payload Base64 디코딩에서 userId Long 값을 반환한다"");
A.push("    - "SessionManager.hasToken()이 토큰 존재 여부를 boolean으로 반환한다"");
A.push("    - "SessionManager.clear()가 토큰과 userId를 모두 삭제한다"");
A.push("  artifacts:");A.push("    - path: "app/src/main/java/com/mindJellyProject/mindjelly/common/SessionManager.java"");
A.push("      provides: "JWT 저장/조회/삭제 + userId 추출"");A.push("      exports: ["getInstance(Context)","saveToken(String)","getToken()","getUserId()","hasToken()","clear()"]");
A.push("    - path: "gradle/libs.versions.toml"");A.push("      contains: "security-crypto"");A.push("    - path: "app/build.gradle"");A.push("      contains: "security.crypto"");
A.push("  key_links:");A.push("    - from: "SessionManager.getUserId()"");A.push("      to: "JWT payload"");A.push("      via: "android.util.Base64 디코딩 후 JSONObject 파싱"");
A.push("---");A.push("");A.push("## Phase Goal");A.push("");
A.push("**As a** MindJelly 사용자, **I want to** 앱을 재시작해도 로그인 상태가 유지되기를, **so that** 매번 다시 로그인하지 않아도 된다.");A.push("");
A.push("<objective>");A.push("SessionManager.java를 신규 생성하고 EncryptedSharedPreferences 기반 JWT 저장소를 구축한다.");
A.push("AuthInterceptor(Plan B), LoginActivity 완성(Plan C), userId 제거(Plan E) 모두가 이 파일에 의존한다.");A.push("");
A.push("Purpose: JWT 토큰을 암호화 저장하고 payload에서 userId를 추출하는 단일 진입점 제공");
A.push("Output: SessionManager.java (신규), gradle 의존성 추가");A.push("</objective>");A.push("");
