const fs=require("fs"),b=".planning/phases/01-auth";
const A=[];
A.push("---");A.push("phase: 01-auth");A.push("plan: A");A.push("type: execute");A.push("wave: 1");A.push("depends_on: []");
A.push("files_modified:");A.push("  - gradle/libs.versions.toml");A.push("  - app/build.gradle");
A.push("  - app/src/main/java/com/mindJellyProject/mindjelly/common/SessionManager.java");
A.push("autonomous: true");A.push("requirements:");A.push("  - AUTH-03");A.push("  - QUAL-05");A.push("");
A.push("must_haves:");A.push("  truths:");
A.push("    - \"앱 재시작 후에도 JWT 토큰이 EncryptedSharedPreferences에서 복원된다\"");
A.push("    - \"SessionManager.getToken()이 저장된 토큰 문자열을 반환한다\"");
A.push("    - \"SessionManager.getUserId()가 JWT payload Base64 디코딩에서 userId Long 값을 반환한다\"");
A.push("    - \"SessionManager.hasToken()이 토큰 존재 여부를 boolean으로 반환한다\"");
A.push("    - \"SessionManager.clear()가 토큰과 userId를 모두 삭제한다\"");
A.push("  artifacts:");
A.push("    - path: \"app/src/main/java/com/mindJellyProject/mindjelly/common/SessionManager.java\"");
A.push("      provides: \"JWT 저장/조회/삭제 + userId 추출\"");
A.push("      exports: [\"getInstance(Context)\", \"saveToken(String)\", \"getToken()\", \"getUserId()\", \"hasToken()\", \"clear()\"]");
A.push("    - path: \"gradle/libs.versions.toml\"");A.push("      provides: \"security-crypto 버전 정의\"");A.push("      contains: \"security-crypto\"");
A.push("    - path: \"app/build.gradle\"");A.push("      provides: \"security-crypto 의존성 선언\"");A.push("      contains: \"security.crypto\"");
A.push("  key_links:");
A.push("    - from: \"SessionManager.getUserId()\"");A.push("      to: \"JWT payload\"");
A.push("      via: \"android.util.Base64 디코딩 후 JSONObject 파싱\"");A.push("      pattern: \"Base64.decode\"");
A.push("    - from: \"SessionManager\"");A.push("      to: \"EncryptedSharedPreferences\"");
A.push("      via: \"MasterKey + EncryptedSharedPreferences.create()\"");A.push("      pattern: \"EncryptedSharedPreferences.create\"");
A.push("---");A.push("");A.push("## Phase Goal");A.push("");
A.push("**As a** MindJelly 사용자, **I want to** 앱을 재시작해도 로그인 상태가 유지되기를, **so that** 매번 다시 로그인하지 않아도 된다.");
A.push("");A.push("<objective>");
A.push("SessionManager.java를 신규 생성하고 EncryptedSharedPreferences 기반 JWT 저장소를 구축한다.");
A.push("AuthInterceptor(Plan B), LoginActivity 완성(Plan C), userId 제거(Plan E) 모두가 이 파일에 의존한다.");
A.push("");A.push("Purpose: JWT 토큰을 암호화 저장하고 payload에서 userId를 추출하는 단일 진입점 제공");
A.push("Output: SessionManager.java (신규), gradle 의존성 추가");A.push("</objective>");A.push("");
A.push("<execution_context>");A.push("@$HOME/.claude/get-shit-done/workflows/execute-plan.md");A.push("@$HOME/.claude/get-shit-done/templates/summary.md");A.push("</execution_context>");A.push("");
A.push("<context>");A.push("@.planning/PROJECT.md");A.push("@.planning/ROADMAP.md");A.push("@.planning/phases/01-auth/01-CONTEXT.md");A.push("");
A.push("<interfaces>");
A.push("From app/src/main/java/com/mindJellyProject/mindjelly/common/Resource.java:");
A.push("  public class Resource<T>");A.push("    public static <T> Resource<T> success(T data)");A.push("    public static <T> Resource<T> error(String error)");
A.push("    public T getData()");A.push("    public String getError()");A.push("");
A.push("From gradle/libs.versions.toml (현재 없는 항목 -- 추가 대상):");
A.push("  [versions] 섹션에 securityCrypto = \"1.1.0-alpha06\" 추가 필요");
A.push("  [libraries] 섹션에 security-crypto 라이브러리 항목 추가 필요");A.push("");
A.push("From app/build.gradle (현재 없는 항목 -- 추가 대상):");
A.push("  implementation libs.security.crypto 추가 필요");A.push("</interfaces>");A.push("</context>");A.push("");
A.push("<tasks>");A.push("");A.push("<task type=\"auto\">");
A.push("  <name>Task 1: security-crypto 의존성 추가</name>");
A.push("  <files>gradle/libs.versions.toml, app/build.gradle</files>");
A.push("  <read_first>");
A.push("    - gradle/libs.versions.toml -- 현재 [versions], [libraries] 섹션 전체 구조 확인 후 삽입 위치 파악");
A.push("    - app/build.gradle -- 현재 dependencies 블록 확인 후 삽입 위치 파악");
A.push("  </read_first>");A.push("  <action>");
A.push("    gradle/libs.versions.toml의 [versions] 섹션에 다음 항목을 추가한다:");
A.push("      securityCrypto = \"1.1.0-alpha06\"");A.push("");
A.push("    같은 파일 [libraries] 섹션에 다음 항목을 추가한다:");
A.push("      security-crypto = { group = \"androidx.security\", name = \"security-crypto\", version.ref = \"securityCrypto\" }");A.push("");
A.push("    app/build.gradle의 dependencies 블록 안에 다음 줄을 추가한다:");
A.push("      implementation libs.security.crypto");A.push("");
A.push("    주의: libs.versions.toml의 하이픈(security-crypto)은 build.gradle에서 점(security.crypto)으로 접근한다.");
A.push("    minSdk가 31이므로 alpha06 버전 호환성 문제 없음 (minSdk 23+ 요구).");
A.push("  </action>");A.push("  <verify>");
A.push("    gradle/libs.versions.toml에 \"securityCrypto\" 문자열이 포함되어 있다.");
A.push("    gradle/libs.versions.toml에 \"androidx.security\" 문자열이 포함되어 있다.");
A.push("    app/build.gradle에 \"security.crypto\" 문자열이 포함되어 있다.");
A.push("  </verify>");A.push("  <acceptance_criteria>");
A.push("    private 생성자(Context): MasterKey.Builder + AES256_GCM으로 masterKey 생성.");
A.push("  <acceptance_criteria>");
A.push("    - libs.versions.toml securityCrypto = \"1.1.0-alpha06\" 라인 존재");
A.push("    - libs.versions.toml security-crypto 라이브러리 라인 존재");
A.push("    - build.gradle implementation libs.security.crypto 라인 존재");
A.push("  </acceptance_criteria>");
A.push("  <done>Gradle sync 후 EncryptedSharedPreferences 임포트 컴파일 오류 없이 해결</done>");
A.push("</task>");A.push("");
A.push("<task type=\"auto\">");
A.push("  <name>Task 2: SessionManager.java 신규 생성</name>");
A.push("  <files>app/src/main/java/com/mindJellyProject/mindjelly/common/SessionManager.java</files>");
A.push("  <read_first>");
A.push("    - app/src/main/java/com/mindJellyProject/mindjelly/common/RetrofitClient.java -- 기존 패턴 참고");
A.push("    - app/src/main/java/com/mindJellyProject/mindjelly/common/Resource.java -- 패키지 위치 확인");
A.push("  </read_first>");
A.push("  <action>");
